### ISSUE TITLE
Jdeps wrong path on Arch Linux

### ISSUE THREAD

**Issue by Nuss9940** [janScheible/pocketsaw#28]
Unit test fails on an Arch Linux system:

``java.io.UncheckedIOException: java.io.IOException: Cannot run program "/usr/lib/jvm/java-11-openjdk/../bin/jdeps": error=2, No such file or directory``

The correct path on my system is:

    $ which jdeps
    /usr/lib/jvm/default/bin/jdeps

(This is a symlink, on Arch Linux you can easily change the Java version using a script)

Or the direct path:

    $ /usr/lib/jvm/java-11-openjdk/bin/jdeps -version
    11.0.4

JAVA_HOME is not set

    jshell> System.getProperty("java.home");
    $1 ==> "/usr/lib/jvm/java-11-openjdk"

It seems like the system property does not include the bin directory while the environment variable does.

**Comment by janScheible** [comment]
Thanks for the detailed bug report.
Seems to be a jdk8 vs. jdk11 issue (also visible on my Windows machine).
For jdk8 `java.home` property is `../jdk-8/jre` but for jdk11 it is `../jdk-11`.
I'll create a fix for that in the next days...

**Comment by Nuss9940** [comment]
Thank you very much for the fix, works as expected.
